version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
      - '8080:8080'
      - '443:443'
    depends_on:
      - api
    restart: always

  api:
    build: ./src
    ports:
      - '5000'
    restart: always
